#
# Module manifest for module 'MacAddress'
#
# Generated by: Saw-friendship
#
# Generated on: 2023-01-09
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'MacAddress.psm1'

    # Version number of this module.
    ModuleVersion     = '2.0.3'

    # ID used to uniquely identify this module
    GUID              = 'ee2dd8a5-8439-4156-8073-583864eb2d25'

    # Author of this module
    Author            = 'Saw-Friendship'

    # Copyright statement for this module
    Copyright         = 'Saw-Friendship'

    # Company or vendor of this module
    # CompanyName = ''

    # Description of the functionality provided by this module
    Description       = 'Get Hardware Vendor by MacAddress. Contains Database from IEEE site for offline using. Use Update-MacAddressDatabase commandlet for update Database'

    # Functions to export from this module
    FunctionsToExport = @('Get-MacAddressVendor', 'Update-MacAddressDatabase')

    # Aliases to export from this module
    AliasesToExport   = 'Resolve-MacAddress'

    # Minimum version of the Windows PowerShell engine required by this module
    # PowerShellVersion = ''

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = ''

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Cmdlets to export from this module
    CmdletsToExport   = '*-*'

    # Variables to export from this module
    # VariablesToExport = '*'

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData       = @{}

    # HelpInfo URI of this module
    # HelpInfoURI = 'https://sawfriendship.wordpress.com/2017/06/07/powershell-mac-address-vendor-database-ieee/'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

